### ISSUE TITLE
Do not reveal next section on exercise completion

### ISSUE THREAD

**Issue by robbyshaver** [rstudio/tutor#35]
Garrett suggests that students should always have to press the skip/go on button to reveal the next exercise.

Questions:
- Would we make this an option? i.e. Are there cases where the current behavior of revealing the next exercise on completion is preferable?
- If skip is not enabled, would the button only appear (or be enabled) once the exercise is completed? Yes.

**Comment by garrettgman** [comment]
In an offline discussion, Robby and I clarified the guiding principles here (and in #32, #33, and #34):

Progressive reveal and allow skip are two separate features:

* Progressive reveal gives *students* control over the rate at which they receive new information. It is based on an educational finding that students learn better when they actively control when to move on. Example:

    + A student finishes an exercise and then reflects on why their guess turned out to be the right answer before they click "Go On" to see the next bit of material.

* Allow skip gives *teachers* control over whether students must do the exercises. Teachers can use this when the next section reveals the answer to the current exercise. Example:

    + A student would like to go on to the next section, but the "Go On" button is greyed out and will remain so until they complete the current exercise.


Applied to the questions above:

> Would we make this an option? i.e. Are there cases where the current behavior of revealing the next exercise on completion is preferable?

I do not think this should be an option for three reasons.

1. To accord with learning theory, progressive reveal should always wait for students to click "Go On":
    1. At the end of every exercise, and
    2. At the beginning of every new sub-section
2. By imposing a consistent behavior, we can help students learn how to navigate tutorials quickly (every tutorial they meet that uses progressive reveal will work in the same way).
3. it will simplify the implementation: Every exercise is followed by a "Go On" button. In the case described in the question, we would need to create an alternative visual object to follow some exercises. This object would be needed to alert the student that more material will be revealed when they complete the exercise.

> If skip is not enabled, would the button only appear (or be enabled) once the exercise is completed? Yes.

I agree; yes. I also suggest that we make `allow_skip: true` be the default.

**Comment by robbyshaver** [comment]
FIxed - you must now press the "Continue" button to reveal the next section.

**Comment by jjallaire** [comment]
We should make sure that all of the section revealing/skipping is integrated with the event system so that when a topic is skipped (or a section revealed) this persists the next time the user loads the tutorial.

@robbyshaver I know I put in a skipExercise function for this behavior, but are you able to use that with sections and still get all the events back correctly on reload. If not just post an issue and I'll look at it when I'm back from SF next week.
